language: node_js
branches:
    only:
        - master
cache:
    directories:
        - node_modules
before_install:
    - npm install -g node-gyp
    - npm update
install:
    - npm install
script:
    - npm test
    - npm run coveralls