language: node_js
node_js:
    - node
    - lts/*
branches:
    only:
        - master
        - develop
sudo: required
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5.0
env:
    - CXX=g++-5.0
cache:
    directories:
        - node_modules
before_install:
    - npm update
install:
    - npm install
script:
    - npm run test
after-script:
    - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls